name: Build MuPDF binary for Windows
runs:
  using: "composite"
  steps:
    - name: Setup JDK and Gradle
      uses: ./.github/actions/setup-java-gradle
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3
    - name: Build binary
      run: ./gradlew :lib:desktopResourceWindowsX86 :lib:desktopResourceWindowsAMD64
    - name: Upload Windows library
      uses: actions/upload-artifact@v7
      with:
        name: windows
        path: lib/src/jvmMain/resources/
        compression-level: 0
