config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: ['my_rule_set', '.*>.*>[my_property]']
  excludes: [ ]

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'ProjectCognitiveComplexityProcessor'
  # - 'ProjectLLOCProcessor'
  # - 'ProjectCLOCProcessor'
  # - 'ProjectLOCProcessor'
  # - 'ProjectSLOCProcessor'
  # - 'LicenseHeaderLoaderExtension'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'IssuesReport'
    - 'FileBasedIssuesReport'
  #  - 'LiteIssuesReport'

comments:
  active: true

complexity:
  active: false

coroutines:
  active: true
  InjectDispatcher:
    active: false

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false

naming:
  active: true
  # Configuration for Compose
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  # Configuration for Compose
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Za-z0-9]*'
  MatchingDeclarationName:
    active: true
    multiplatformTargets: [ 'android','jvm','desktop' ]

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  UnusedPrivateFunction:
    active: true
    ignoreAnnotated: [ 'Preview', 'Provides', 'PreviewMultiplatform' ]
  UnusedPrivateProperty:
    active: false # TODO バグ？
    allowedNames: 'ignored|expected|serialVersionUID|bind'

# https://mrmans0n.github.io/compose-rules/detekt/
Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
    allowedCompositionLocals: [
      'LocalAppLocaleIsoInternal',
      'LocalAppState',
      'LocalComposeEffectErrorHandler',
      'LocalDimension',
      'LocalNavigationItems',
      'LocalNavigator',
      'LocalPlatformContext',
      'LocalSharedTransitionScope',
    ]
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: true
  ContentSlotReused:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterEventTrailing:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2:
    active: true # Opt-in, disabled by default. Turn on if you want to disallow Material 2 usages.
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewNaming:
    active: true
    previewNamingStrategy: suffix
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  UnstableCollections:
    active: false
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true

ktlint:
  active: true
  code_style: 'android_studio'
  autoCorrect: true
  MaximumLineLength:
    # See [style.MaxLineLength]
    active: false
  PropertyName:
    # See [naming.PropertyName]
    active: false
  TrailingCommaOnCallSite:
    active: true
    useTrailingCommaOnCallSite: true
  TrailingCommaOnDeclarationSite:
    active: true
    useTrailingCommaOnDeclarationSite: true
