name: Build
on:
  workflow_call:

jobs:

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run publishAndroidReleasePublicationToMavenLocal
        run: ./gradlew :lib:publishAndroidReleasePublicationToMavenLocal
      - name: Run assembleDebug
        run: ./gradlew assembleDebug
      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: mupdf-kmp-android
          path: ~/.m2/repository/
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: composeApp-debug.apk
          path: composeApp/build/outputs/apk/debug/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Run buildJavaviewerlib
        run: ./gradlew :lib:addUtf8BomToFiles :lib:desktopResourceWindowsX86 :lib:desktopResourceWindowsAMD64
      - name: Upload Windows library
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: lib/src/jvmMain/resources/
          compression-level: 0

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype-dev
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run buildJavaviewerlib
        run: ./gradlew :lib:desktopResourceLinuxAMD64
      - name: Upload Linux library
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: lib/src/jvmMain/resources/
          compression-level: 0

  build-desktop:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs:
      - build-windows
      - build-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: lib/src/jvmMain/resources/
          merge-multiple: true
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: lib/src/jvmMain/resources/
          merge-multiple: true
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run publishJvmPublicationToMavenLocal
        run: ./gradlew :lib:publishJvmPublicationToMavenLocal
      - name: Run packageDistributionForCurrentOS
        run: ./gradlew :composeApp:packageDistributionForCurrentOS
      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: mupdf-kmp-jvm-${{ runner.os }}
          path: ~/.m2/repository/
      - name: Upload Desktop Binaries
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ runner.os }}
          path: composeApp/build/compose/binaries/main/

  check-build:
    name: All Build Passed
    runs-on: ubuntu-latest
    needs: [ build-android, build-desktop ]
    steps:
      - name: Confirm All Build Jobs Succeeded
        run: echo "✅ All build jobs (Android, Windows, macOS, Linux) completed successfully."
