name: Lint
on:
  workflow_call:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ Debug, Release ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: 🚨Run lint
        run: ./gradlew composeApp:lint${{ matrix.variant }} lib:lint${{ matrix.variant }}
      - name: Upload Lint SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: build/reports/lint/lint-result.sarif
          category: android-lint

  lint-aggregate:
    name: All Lint Checks Passed
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Confirm All Lint Jobs Succeeded
        run: echo "✅ All lint jobs succeeded!"
