name: Build MuPDF
on:
    workflow_call:

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup JDK and Gradle
              uses: ./.github/actions/setup-java-gradle
            - name: Run buildJavaviewerlib
              run: ./gradlew :lib:addUtf8BomToFiles :lib:buildJavaviewerlibx86 :lib:buildJavaviewerlibx64
            - name: Upload Windows dll
              uses: actions/upload-artifact@v4
              with:
                  name: windows
                  path: lib/src/jvmMain/resources/

    build-android:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup JDK and Gradle
              uses: ./.github/actions/setup-java-gradle
            - name: Run buildJavaviewerlib
              run: ./gradlew :lib:addUtf8BomToFiles :lib:buildJavaviewerlibx86 :lib:buildJavaviewerlibx64
            - name: Upload Windows dll
              uses: actions/upload-artifact@v4
              with:
                  name: windows
                  path: lib/src/jvmMain/resources/
