name: Build MuPDF

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-native-lib:
    strategy:
      matrix:
        include:
          - arch: 'x86'
            os: 'windows'
            runs_on: 'windows-latest'
            task: ':lib:desktopResourceWindowsX86'
          - arch: 'x64'
            os: 'windows'
            runs_on: 'windows-latest'
            task: ':lib:desktopResourceWindowsAMD64'
          - arch: 'x64'
            os: 'linux'
            runs_on: 'ubuntu-latest'
            task: ':lib:desktopResourceLinuxAMD64'
      runs-on: ${{ matrix.runs_on }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Setup JDK and Gradle
          uses: ./.github/actions/setup-java-gradle
        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v2
        - name: Run addUtf8BomToFiles (windows only)
          if: contains(matrix.os, 'windows')
          run: ./gradlew :lib:addUtf8BomToFiles
        - name: Run ${{ matrix.task }}
          run: ./gradlew ${{ matrix.task }}
        - name: Upload Windows library
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.os }}-${{ matrix.arch }}
            path: lib/src/jvmMain/resources/
            compression-level: 0
            retention-days: 1

  publish:
    needs:
      - build-native-lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: lib/src/jvmMain/resources/
          merge-multiple: true
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: lib/src/jvmMain/resources/
          merge-multiple: true
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run publishToMavenLocal
        run: ./gradlew :lib:publishAndroidReleasePublicationToMavenLocal :lib:publishJvmPublicationToMavenLocal
      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: ~/.m2/repository/
