name: Publish Maven Central

on:
  push:
    branches:
      - main
  release:
    types: [ published ]

permissions:
  contents: read
  pull-requests: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-windows-binary:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build MuPDF binary for Windows
        uses: ./.github/actions/build-windows-binary

  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build MuPDF binary for Windows
        uses: ./.github/actions/build-linux-binary

  publish:
    if: github.event_name == 'release'
    needs:
      - build-windows-binary
      - build-linux-binary
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          path: lib/src/jvmMain/resources/
          merge-multiple: true
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: 🚀 Run publish
        run: ./gradlew :lib:android:publishAndReleaseToMavenCentral :lib:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralAutomaticPublishing: ${{ vars.ORG_GRADLE_PROJECT_MAVENCENTRALAUTOMATICPUBLISHING }}
          ORG_GRADLE_PROJECT_signAllPublications: true

  publish-snapshot:
    if: github.event_name != 'release'
    needs:
      - build-windows-binary
      - build-linux-binary
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          path: lib/src/jvmMain/resources/
          merge-multiple: true
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: 🚀 Run publish snapshot
        run: ./gradlew :lib:android:publishMavenPublicationToMavenCentralRepository :lib:publishAllPublicationsToMavenCentralRepository --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralAutomaticPublishing: ${{ vars.ORG_GRADLE_PROJECT_MAVENCENTRALAUTOMATICPUBLISHING }}
          ORG_GRADLE_PROJECT_signAllPublications: false

