name: Static Code Analysis
on:
  workflow_call:

jobs:

  detekt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ detektAndroidAll, detektDesktopAll, detektMetadataAll, ':build-logic:detektAll' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: 🔍️Run detekt
        run: ./gradlew ${{ matrix.task }}
      - name: Upload Detekt SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() && matrix.task != ':build-logic:detektAll' }}
        with:
          sarif_file: build/reports/detekt/merge.sarif
          category: detekt
      - name: Upload Detekt SARIF(build-logic)
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() && matrix.task == ':build-logic:detektAll' }}
        with:
          sarif_file: build-logic/build/reports/detekt/detekt.sarif
          category: detekt

  checkVersionCatalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run check VersionCatalog
        run: ./gradlew checkVersionCatalog

  static-code-analysis-aggregate:
    name: All Static Code Analysis Checks Passed
    runs-on: ubuntu-latest
    needs: [ detekt, checkVersionCatalog ]
    steps:
      - name: Confirm All Static Code Analysis Jobs Succeeded
        run: echo "✅ All static code analysis jobs succeeded!"
