name: tmp

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
#  clear:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Delete Branch Cache
#        uses: snnaplab/delete-branch-cache-action@v1
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: describe
        run: git describe --tags --abbrev=1 --always

      - name: 🚨Run lint
        run: ./gradlew clean build --no-configuration-cache
