name: tmp

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: describe tag
        run: git describe --tags --abbrev=1

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: 🚨Run lint
        run: ./gradlew lintAndroidMain
